mutation addOneTask ($title: String!, $content: String, $dueDate: String, $tags: String, $createdBy: String) {
  createTask (
    title: $title,
    content: $content,
    dueDate: $dueDate,
    tags: $tags,
    createdBy: $createdBy
  ) {
      id
  }
}