mutation AddTask ($title: String!, $content: String, $dueDate: String, $tags: String, $user: String) {
  createTask (
    title: $title,
    content: $content,
    dueDate: $dueDate,
    tags: $tags,
    user: $user
  ) {
      id
  }
}