mutation addUser($name: String!, $email: String, $lives: String) {
    createOneUser(
        data: {
            name: $name
            email: $email
            lives: $lives
        }
    ) {
		name,
		email,
		lives
    }
}