mutation updateOneTask ($id: String!, $title: String!, $content: String, $dueDate: String, $tags: String, $createdBy: String) {
  updateTask (where:
    { id: $id},
    data: { 
    title: $title,
    content: $content,
    dueDate: $dueDate,
    tags: $tags,
    createdBy: $createdBy
    }
  ) {
      id
  }
}